// stories/vue/Horizontal.vue
<script setup lang="ts">
import { ref } from 'vue'
import { VList } from '../../src/vue'

const sizes = [40, 180, 77];
const createItem = (i: number) => ({ index: i, size: sizes[i % 3] + 'px' })

const data = ref(Array.from({ length: 1000 }).map((_, i) => createItem(i)));

</script>

<template>
  <div :style="{ padding: '10px' }">
    <VList :data="data" :style="{ width: '100%', height: '200px' }" horizontal>
      <template #default="item">
        <div :key="item.index" :style="{ width: item.size, background: 'white', borderRight: 'solid 1px #ccc' }">
          {{ item.index }}
        </div>
      </template>
    </VList>
  </div>
</template>

<style scoped>
/* NOP */
</style>

// stories/svelte/Horizontal.svelte
<script lang="ts">
  import { VList } from "../../src/svelte";

  const sizes = [40, 180, 77];
  const createItem = (i: number) => ({ id: i, size: sizes[i % 4] + "px" });

  const data = Array.from({ length: 1000 }).map((_, i) => createItem(i));
</script>

<div style="padding: 10px;">
  <VList
    {data}
    let:item
    style={`width: 100%; height: 200px;`}
    getKey={(d) => d.id}
    horizontal
  >
    <div
      style={`
      width: ${item.size};
      background: white;
      border-right: solid 1px #ccc;
    `}
    >
      {item.id}
    </div>
  </VList>
</div>
