// stories/svelte/basics/Nested.svelte
<script lang="ts">
  import { Virtualizer } from "../../../src/svelte";

  const sizes = [20, 40, 80, 77];

  const data = Array.from({ length: 1000 }).map((_, i) => sizes[i % 4]!);

  const outerPadding = 40;
  const innerPadding = 60;
  let scrollRef: HTMLElement = $state();
</script>

<div
  bind:this={scrollRef}
  style={`
  width: 100%;
  height: 100vh;
  overflow-y: auto;
  /* opt out browser's scroll anchoring on header/footer because it will conflict with scroll anchoring of virtualizer */
  overflow-anchor: none;
`}
>
  <div style="background-color: burlywood; padding: {outerPadding}px;">
    <div style="background-color: steelblue; padding: {innerPadding}px;">
      <Virtualizer
        {data}
        getKey={(_, i) => i}
        {scrollRef}
        startMargin={outerPadding + innerPadding}
      >
        {#snippet children(item, index)}
          <div
            style="
              height: {item}px;
              background: white;
              border-bottom: solid 1px #ccc;
            "
          >
            {index}
          </div>
        {/snippet}
      </Virtualizer>
    </div>
  </div>
</div>

// stories/angular/basics/Nested.ts
import { Component } from "@angular/core";
import { Virtualizer } from "../../../src/angular";

const sizes = [20, 40, 80, 77];

@Component({
  selector: "story-nested",
  imports: [Virtualizer],
  template: `
    <div
      #scrollable
      style="
        width: 100%;
        height: 100vh;
        overflow-y: auto;
        /* opt out browser's scroll anchoring on header/footer because it will conflict with scroll anchoring of virtualizer */
        overflow-anchor: none;
      "
    >
      <div
        [style.padding.px]="outerPadding"
        style="background-color: burlywood;"
      >
        <div
          [style.padding.px]="innerPadding"
          style="background-color: steelblue;"
        >
          <div
            virtuaVirtualizer
            [data]="data"
            [getKey]="getKey"
            [scrollRef]="scrollable"
            [startMargin]="outerPadding + innerPadding"
          >
            <ng-template let-item let-index="index">
              <div
                [style.height.px]="item"
                style="background: white; border-bottom: solid 1px #ccc;"
              >
                {{ index }}
              </div>
            </ng-template>
          </div>
        </div>
      </div>
    </div>
  `,
})
export class NestedDemo {
  protected readonly data = Array.from({ length: 1000 }).map(
    (_, i) => sizes[i % 4]!,
  );
  protected readonly getKey = (_: number, i: number) => i;
  protected readonly outerPadding = 40;
  protected readonly innerPadding = 60;
}
