// stories/svelte/WindowVirtualizer.svelte
<script lang="ts">
  import { WindowVirtualizer } from "../../src/svelte";

  const sizes = [20, 40, 180, 77];

  const data = Array.from({ length: 1000 }).map((_, i) => sizes[i % 4]!);
</script>

<div style="padding: 200px 100px;">
  <div style="border: solid 1px gray;">
    <WindowVirtualizer {data} getKey={(_, i) => i}>
      {#snippet children(item, index)}
        <div
          style={`
            height: ${item}px;
            background: white;
            border-bottom: solid 1px #ccc;
          `}
        >
          {index}
        </div>
      {/snippet}
    </WindowVirtualizer>
  </div>
</div>

// stories/angular/basics/WindowVirtualizer.ts
import { Component } from "@angular/core";
import { WindowVirtualizer } from "../../../src/angular";

const sizes = [20, 40, 180, 77];

@Component({
  selector: "story-window-virtualizer",
  imports: [WindowVirtualizer],
  template: `
    <div style="padding: 200px 100px;">
      <div style="border: solid 1px gray;">
        <virtua-window-virtualizer [data]="data" [getKey]="getKey">
          <ng-template let-item let-index="index">
            <div
              [style.height.px]="item"
              style="background: white; border-bottom: solid 1px #ccc;"
            >
              {{ index }}
            </div>
          </ng-template>
        </virtua-window-virtualizer>
      </div>
    </div>
  `,
})
export class WindowVirtualizerDemo {
  protected readonly data = Array.from({ length: 1000 }).map(
    (_, i) => sizes[i % 4]!,
  );
  protected readonly getKey = (_: number, i: number) => i;
}
