// src/solid/Virtualizer.tsx
/**
 * @jsxImportSource solid-js
 */
import {
  onMount,
  onCleanup,
  createEffect,
  createSignal,
  createMemo,
  type JSX,
  on,
  createComputed,
  type ValidComponent,
  mergeProps,
  For,
  type Accessor,
  untrack,
} from "solid-js";
import { Dynamic, isServer } from "solid-js/web";
import {
  UPDATE_SCROLL_EVENT,
  UPDATE_SCROLL_END_EVENT,
  UPDATE_VIRTUAL_STATE,
  createVirtualStore,
  createListLayout,
  ACTION_ITEMS_LENGTH_CHANGE,
  getScrollSize,
  ACTION_START_OFFSET_CHANGE,
  createContainerDriver,
  scrollTo,
  scrollBy,
  scrollToIndex,
  type ItemsRange,
  type ScrollToIndexOpts,
  type CacheSnapshot,
  sort,
} from "../core/index.js";
import { ListItem } from "./ListItem.js";
import { isSameRange } from "./utils.js";

/**
 * Methods of {@link Virtualizer}.
 */
export interface VirtualizerHandle {
  /**
   * Get current {@link CacheSnapshot}.
   */
  readonly cache: CacheSnapshot;
  /**
   * Get current scrollTop, or scrollLeft if horizontal: true. Always positive even in RTL.
   */
  readonly scrollOffset: number;
  /**
   * Get current scrollHeight, or scrollWidth if horizontal: true.
   */
  readonly scrollSize: number;
  /**
   * Get current clientHeight, or clientWidth if horizontal: true.
   */
  readonly viewportSize: number;
  /**
   * Find nearest item index from offset.
   * @param offset offset in pixels from the start of the scroll container
   */
  findItemIndex(offset: number): number;
  /**
   * Get item offset from start.
   * @param index index of item
   */
  getItemOffset(index: number): number;
  /**
   * Get item size.
   * @param index index of item
   */
  getItemSize(index: number): number;
  /**
   * Scroll to the item specified by index.
   * @param index index of item
   * @param opts options
   */
  scrollToIndex(index: number, opts?: ScrollToIndexOpts): void;
  /**
   * Scroll to the given offset.
   * @param offset offset from start
   */
  scrollTo(offset: number): void;
  /**
   * Scroll by the given offset.
   * @param offset offset from current position
   */
  scrollBy(offset: number): void;
}

/**
 * Props of {@link Virtualizer}.
 */
export interface VirtualizerProps<T> {
  /**
   * Get reference to {@link VirtualizerHandle}.
   */
  ref?: VirtualizerHandle | ((handle?: VirtualizerHandle) => void);
  /**
   * The data items rendered by this component.
   */
  data: readonly T[];
  /**
   * The elements renderer function.
   */
  children: (data: T, index: Accessor<number>) => JSX.Element;
  /**
   * Extra item space in pixels to render before/after the viewport. The minimum value is 0. Lower value will give better performance but you can increase to avoid showing blank items in fast scrolling.
   * @defaultValue 200
   */
  bufferSize?: number;
  /**
   * Component or element type for container element.
   * @defaultValue "div"
   */
  as?: ValidComponent;
  /**
   * Component or element type for item element.
   * @defaultValue "div"
   */
  item?: ValidComponent;
  /**
   * Reference to the scrollable element. The default will get the direct parent element of virtualizer.
   */
  scrollRef?: HTMLElement;
  /**
   * Item size hint for unmeasured items in pixels. It will help to reduce scroll jump when items are measured if used properly.
   *
   * - If not set, initial item sizes will be automatically estimated from measured sizes. This is recommended for most cases.
   * - If set, you can opt out estimation and use the value as initial item size.
   */
  itemSize?: number;
  /**
   * A prop for SSR. If set, the specified amount of items will be mounted in the initial rendering regardless of the container size until hydrated. The minimum value is 0.
   */
  ssrCount?: number;
  /**
   * Set true only when items are added to or removed from the start of the list, such as when older items are loaded in reverse infinite scrolling. In that case, the scroll position is maintained from the end of the list instead of the start.
   *
   * **Do not set true in any other case, as it can cause unexpected behavior.**
   */
  shift?: boolean;
  /**
   * If true, rendered as a horizontally scrollable list. Otherwise rendered as a vertically scrollable list.
   */
  horizontal?: boolean;
  /**
   * List of indexes that should be always mounted, even when off screen.
   */
  keepMounted?: readonly number[];
  /**
   * You can restore cache by passing a {@link CacheSnapshot} on mount. This is useful when you want to restore scroll position after navigation. The snapshot can be obtained from {@link VirtualizerHandle.cache}.
   *
   * **The length of items should be the same as when you take the snapshot, otherwise restoration may not work as expected.**
   */
  cache?: CacheSnapshot;
  /**
   * The offset to the scrollable parent before virtualizer in pixels. If you put an element before virtualizer, you have to set its height to this prop.
   */
  startMargin?: number;
  /**
   * Callback invoked whenever scroll offset changes.
   * @param offset Current scrollTop, or scrollLeft if horizontal: true.
   */
  onScroll?: (offset: number) => void;
  /**
   * Callback invoked when scrolling stops.
   */
  onScrollEnd?: () => void;
}

/**
 * Customizable list virtualizer for advanced usage. See {@link VirtualizerProps} and {@link VirtualizerHandle}.
 */
export const Virtualizer = <T,>(props: VirtualizerProps<T>): JSX.Element => {
  let containerRef: HTMLDivElement | undefined;
  const { itemSize, horizontal = false, cache, ssrCount } = props;
  props = mergeProps<[Partial<VirtualizerProps<T>>, VirtualizerProps<T>]>(
    { as: "div" },
    props,
  );

  const [isSSR, setIsSSR] = createSignal(!!ssrCount);

  const layout = createListLayout(props.data.length, itemSize, cache);
  const store = createVirtualStore(layout, ssrCount);
  const driver = createContainerDriver(store, horizontal);

  const [stateVersion, setRerender] = createSignal(store.$getStateVersion());

  store.$subscribe(UPDATE_VIRTUAL_STATE, () => {
    setRerender(store.$getStateVersion());
  });
  store.$subscribe(UPDATE_SCROLL_EVENT, () => {
    props.onScroll?.(store.$getScrollOffset());
  });
  store.$subscribe(UPDATE_SCROLL_END_EVENT, () => {
    props.onScrollEnd?.();
  });

  const range = createMemo<ItemsRange>((prev) => {
    stateVersion();
    const next = store.$getRange(props.bufferSize);
    if (prev && isSameRange(prev, next)) {
      return prev;
    }
    return next;
  });
  const isScrolling = createMemo(() => stateVersion() && store.$isScrolling());
  const totalSize = createMemo(() => stateVersion() && store.$getTotalSize());

  // eslint-disable-next-line solid/reactivity
  const ref = props.ref as Exclude<typeof props.ref, VirtualizerHandle>;
  if (!isServer && ref) {
    ref({
      get cache() {
        return layout.$snapshot();
      },
      get scrollOffset() {
        return store.$getScrollOffset();
      },
      get scrollSize() {
        return getScrollSize(store);
      },
      get viewportSize() {
        return store.$getViewportSize();
      },
      findItemIndex: (offset) =>
        layout.$findIndex(offset - store.$getStartSpacerSize()),
      getItemOffset: store.$getItemOffset,
      getItemSize: store.$getItemSize,
      scrollToIndex: (index, opts) => scrollToIndex(driver, store, index, opts),
      scrollTo: (offset) => scrollTo(driver, offset),
      scrollBy: (offset) => scrollBy(driver, store, offset),
    });
    onCleanup(() => ref());
  }

  onMount(() => {
    setIsSSR(false);

    driver.$observe(containerRef!, props.scrollRef);

    onCleanup(() => {
      store.$dispose();
      driver.$dispose();
    });
  });

  createComputed(
    on(
      () => props.startMargin || 0,
      (value) => {
        if (value !== store.$getStartSpacerSize()) {
          store.$update(ACTION_START_OFFSET_CHANGE, value);
        }
      },
    ),
  );

  createEffect(
    on(stateVersion, () => {
      driver.$effect();
    }),
  );

  const dataSlice = createMemo(() => {
    const count = props.data.length;
    untrack(() => {
      if (count !== store.$getItemsLength()) {
        store.$update(ACTION_ITEMS_LENGTH_CHANGE, [count, props.shift]);
      }
    });
    const items: T[] = [];
    const indexes: number[] = [];

    if (props.keepMounted) {
      const mounted = new Set(props.keepMounted);
      for (let [i, j] = range(); i <= j; i++) {
        mounted.add(i);
      }
      sort([...mounted]).forEach((index) => {
        if (index < count) {
          items.push(props.data[index]!);
          indexes.push(index);
        }
      });
    } else {
      for (let [i, j] = range(); i <= j; i++) {
        items.push(props.data[i]!);
        indexes.push(i);
      }
    }

    return { _items: items, _indexes: indexes };
  });

  const renderItem = (data: T, index: Accessor<number>) => {
    const offset = createMemo(() => {
      stateVersion();
      return store.$getItemOffset(index());
    });
    const hide = createMemo(() => {
      stateVersion();
      return store.$isUnmeasuredItem(index());
    });
    const children = createMemo(() => {
      return untrack(() => props.children(data, index));
    });

    return (
      <ListItem
        _as={props.item}
        _index={index()}
        _resizer={driver.$observeItem}
        _offset={offset()}
        _hide={hide()}
        _children={children()}
        _isHorizontal={horizontal}
        _isSSR={isSSR()}
      />
    );
  };

  return (
    <Dynamic
      component={props.as}
      ref={containerRef}
      style={{
        contain: "size style", // https://github.com/inokawa/virtua/pull/775 https://github.com/inokawa/virtua/issues/800
        "overflow-anchor": "none", // opt out browser's scroll anchoring because it will conflict with scroll anchoring of virtualizer
        flex: "none", // flex style can break layout
        position: "relative",
        width: horizontal ? totalSize() + "px" : "100%",
        height: horizontal ? "100%" : totalSize() + "px",
        "pointer-events": isScrolling() ? "none" : undefined,
      }}
    >
      <For each={dataSlice()._items}>
        {(data, index) => {
          const itemIndex = createMemo(() => dataSlice()._indexes[index()]!);
          // eslint-disable-next-line solid/reactivity
          return renderItem(data, itemIndex);
        }}
      </For>
    </Dynamic>
  );
};

// src/angular/Virtualizer.ts
import {
  ApplicationRef,
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  ElementRef,
  type OnInit,
  TemplateRef,
  afterNextRender,
  afterRenderEffect,
  computed,
  contentChild,
  effect,
  inject,
  input,
  output,
  signal,
  untracked,
} from "@angular/core";
import { NgTemplateOutlet } from "@angular/common";
import {
  ACTION_ITEMS_LENGTH_CHANGE,
  ACTION_START_OFFSET_CHANGE,
  type CacheSnapshot,
  type ScrollToIndexOpts,
  type StateVersion,
  UPDATE_SCROLL_END_EVENT,
  UPDATE_SIZE_EVENT,
  UPDATE_SCROLL_EVENT,
  UPDATE_VIRTUAL_STATE,
  createContainerDriver,
  type Driver,
  scrollTo,
  scrollBy,
  scrollToIndex,
  createVirtualStore,
  createListLayout,
  getScrollSize,
  sort,
} from "../core/index.js";
import { ListItem } from "./ListItem.js";
import {
  ITEM_TEMPLATE,
  defaultGetKey,
  type ItemContext,
  type ItemProps,
} from "./utils.js";

/**
 * Methods of {@link Virtualizer}.
 */
export interface VirtualizerHandle {
  /**
   * Get current {@link CacheSnapshot}.
   */
  readonly cache: CacheSnapshot;
  /**
   * Get current scrollTop, or scrollLeft if horizontal: true. Always positive even in RTL.
   */
  readonly scrollOffset: number;
  /**
   * Get current scrollHeight, or scrollWidth if horizontal: true.
   */
  readonly scrollSize: number;
  /**
   * Get current clientHeight, or clientWidth if horizontal: true.
   */
  readonly viewportSize: number;
  /**
   * Find nearest item index from offset.
   * @param offset offset in pixels from the start of the scroll container
   */
  findItemIndex(offset: number): number;
  /**
   * Get item offset from start.
   * @param index index of item
   */
  getItemOffset(index: number): number;
  /**
   * Get item size.
   * @param index index of item
   */
  getItemSize(index: number): number;
  /**
   * Scroll to the item specified by index.
   * @param index index of item
   * @param opts options
   */
  scrollToIndex(index: number, opts?: ScrollToIndexOpts): void;
  /**
   * Scroll to the given offset.
   * @param offset offset from start
   */
  scrollTo(offset: number): void;
  /**
   * Scroll by the given offset.
   * @param offset offset from current position
   */
  scrollBy(offset: number): void;
}

/**
 * Customizable list virtualizer for advanced usage. See {@link VirtualizerHandle}.
 *
 * The host element is the container of the items. Use the attribute selector to change its tag,
 * like `<ul virtuaVirtualizer [data]="data">`.
 */
@Component({
  selector: "virtua-virtualizer, [virtuaVirtualizer]",
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ListItem, NgTemplateOutlet],
  host: {
    "[style]": "containerStyle()",
  },
  template: `
    @for (item of items(); track item.key) {
      <div
        virtuaListItem
        [index]="item.index"
        [offset]="item.offset"
        [hide]="item.hide"
        [attrs]="item.attrs"
        [horizontal]="horizontal()"
        [isSSR]="isSSR()"
        [resizer]="driver.$observeItem"
      >
        <ng-container
          [ngTemplateOutlet]="template()"
          [ngTemplateOutletContext]="{
            $implicit: item.data,
            index: item.index,
          }"
        />
      </div>
    }
  `,
})
export class Virtualizer<T> implements OnInit, VirtualizerHandle {
  /**
   * The data items rendered by this component.
   */
  readonly data = input.required<readonly T[]>();
  /**
   * Function that returns the key of an item in the list. It's recommended to specify whenever possible for performance.
   * @default defaultGetKey (returns index of item)
   */
  readonly getKey =
    input<(data: T, index: number) => string | number>(defaultGetKey);
  /**
   * A function that provides properties/attributes for item element
   */
  readonly itemProps = input<ItemProps<T>>();
  /**
   * Extra item space in pixels to render before/after the viewport. The minimum value is 0. Lower value will give better performance but you can increase to avoid showing blank items in fast scrolling.
   * @defaultValue 200
   */
  readonly bufferSize = input<number>();
  /**
   * Reference to the scrollable element. The default will get the direct parent element of virtualizer.
   */
  readonly scrollRef = input<HTMLElement>();
  /**
   * Item size hint for unmeasured items in pixels. It will help to reduce scroll jump when items are measured if used properly.
   *
   * - If not set, initial item sizes will be automatically estimated from measured sizes. This is recommended for most cases.
   * - If set, you can opt out estimation and use the value as initial item size.
   */
  readonly itemSize = input<number>();
  /**
   * A prop for SSR. If set, the specified amount of items will be mounted in the initial rendering regardless of the container size until hydrated. The minimum value is 0.
   */
  readonly ssrCount = input<number>();
  /**
   * Set true only when items are added to or removed from the start of the list, such as when older items are loaded in reverse infinite scrolling. In that case, the scroll position is maintained from the end of the list instead of the start.
   *
   * **Do not set true in any other case, as it can cause unexpected behavior.**
   */
  readonly shift = input(false);
  /**
   * If true, rendered as a horizontally scrollable list. Otherwise rendered as a vertically scrollable list.
   */
  readonly horizontal = input(false);
  /**
   * List of indexes that should be always mounted, even when off screen.
   */
  readonly keepMounted = input<readonly number[]>();
  /**
   * You can restore cache by passing a {@link CacheSnapshot} on mount. This is useful when you want to restore scroll position after navigation. The snapshot can be obtained from {@link VirtualizerHandle.cache}.
   *
   * **The length of items should be the same as when you take the snapshot, otherwise restoration may not work as expected.**
   */
  readonly cacheProp = input<CacheSnapshot>(undefined, { alias: "cache" });
  /**
   * The offset to the scrollable parent before virtualizer in pixels. If you put an element before virtualizer, you have to set its height to this prop.
   */
  readonly startMargin = input(0);

  /**
   * Emitted whenever scroll offset changes. The value is current scrollTop, or scrollLeft if horizontal: true.
   */
  readonly scrolled = output<number>();
  /**
   * Emitted when scrolling stops.
   */
  readonly scrollEnded = output<void>();
  /**
   * Emitted when the size of the viewport or the items changes.
   */
  readonly resized = output<void>();

  // not _ prefixed, because the mangler does not rename the property name kept
  // as a string in the partial compilation output
  /** @internal */
  private contentTemplate =
    contentChild<TemplateRef<ItemContext<T>>>(TemplateRef);
  /** @internal */
  private _hostTemplate = inject(ITEM_TEMPLATE, { optional: true });
  /** @internal */
  protected template = computed(
    () => (this._hostTemplate?.() ?? this.contentTemplate())!,
  );

  /** @internal */
  private _store!: ReturnType<typeof createVirtualStore>;
  /** @internal */
  private _layout!: ReturnType<typeof createListLayout>;
  /** @internal */
  protected driver!: Driver;
  /** @internal */
  private _element: HTMLElement = inject(ElementRef).nativeElement;
  /** @internal */
  private _appRef = inject(ApplicationRef);

  /** @internal */
  private _stateVersion = signal<StateVersion>(undefined!);
  /** @internal */
  protected isSSR = signal(false);

  /** @internal */
  private _indexes = computed(() => {
    this._stateVersion(); // the store is not a signal, so depend on its version
    const len = this.data().length;

    const [start, end] = this._store.$getRange(this.bufferSize());
    const keepMounted = this.keepMounted();
    const arr: number[] = [];
    if (keepMounted) {
      const mounted = new Set(keepMounted);
      for (let i = start; i <= end; i++) {
        mounted.add(i);
      }
      for (const index of sort([...mounted])) {
        if (index < len) {
          arr.push(index);
        }
      }
    } else {
      for (let i = start; i <= end; i++) {
        arr.push(i);
      }
    }
    return arr;
  });

  /** @internal */
  protected items = computed(() => {
    this._stateVersion(); // the store is not a signal, so depend on its version
    const store = this._store;
    const data = this.data();
    const getKey = this.getKey();
    const itemProps = this.itemProps();
    return this._indexes().map((index) => {
      const item = data[index]!;
      return {
        key: getKey(item, index),
        index,
        data: item,
        offset: store.$getItemOffset(index),
        hide: this._layout.$isSizeEqual(index),
        attrs: itemProps?.({ item, index }),
      };
    });
  });

  /** @internal */
  protected containerStyle = computed(() => {
    this._stateVersion(); // the store is not a signal, so depend on its version
    const horizontal = this.horizontal();
    const totalSize = this._store.$getTotalSize();
    return {
      display: "block", // host of a custom element is inline by default
      contain: "size style", // https://github.com/inokawa/virtua/pull/775 https://github.com/inokawa/virtua/issues/800
      "overflow-anchor": "none", // opt out browser's scroll anchoring because it will conflict with scroll anchoring of virtualizer
      flex: "none", // flex style can break layout
      position: "relative",
      width: horizontal ? totalSize + "px" : "100%",
      height: horizontal ? "100%" : totalSize + "px",
      "pointer-events": this._store.$isScrolling() ? "none" : undefined,
    };
  });

  constructor() {
    // $effect.pre equivalents: component effects run before this component's template refreshes
    effect(() => {
      const len = this.data().length;
      if (!this._store) return;
      this._store.$update(
        ACTION_ITEMS_LENGTH_CHANGE,
        len,
        untracked(this.shift),
      );
    });
    effect(() => {
      const startMargin = this.startMargin();
      if (!this._store) return;
      if (startMargin !== this._store.$getStartSpacerSize()) {
        this._store.$update(ACTION_START_OFFSET_CHANGE, startMargin);
      }
    });

    // parent's ref may not exist on mount https://github.com/inokawa/virtua/issues/603 https://github.com/inokawa/virtua/issues/690
    afterNextRender({
      read: () => {
        this.isSSR.set(false);
        this.driver.$observe(this._element, this.scrollRef());
      },
    });

    afterRenderEffect({
      read: () => {
        this._stateVersion();
        this.driver.$effect();
      },
    });

    inject(DestroyRef).onDestroy(() => {
      this._store?.$dispose();
      this.driver?.$dispose();
    });
  }

  ngOnInit(): void {
    const itemSize = this.itemSize();
    const ssrCount = this.ssrCount();
    this.isSSR.set(!!ssrCount);
    const layout = (this._layout = createListLayout(
      this.data().length,
      itemSize,
      this.cacheProp(),
    ));
    const store = (this._store = createVirtualStore(layout, ssrCount));
    this.driver = createContainerDriver(store, layout, this.horizontal());
    store.$subscribe(UPDATE_VIRTUAL_STATE, (sync) => {
      this._stateVersion.set(store.$getStateVersion());
      if (sync) {
        // The store requires the DOM to be updated synchronously, otherwise
        // imperative scroll may be clamped by the stale container size.
        this._appRef.tick();
      }
    });
    store.$subscribe(UPDATE_SCROLL_EVENT, () => {
      this.scrolled.emit(store.$getScrollOffset());
    });
    store.$subscribe(UPDATE_SCROLL_END_EVENT, () => {
      this.scrollEnded.emit();
    });
    store.$subscribe(UPDATE_SIZE_EVENT, () => {
      this.resized.emit();
    });
    this._stateVersion.set(store.$getStateVersion());
  }

  get cache(): CacheSnapshot {
    return this._layout.$snapshot();
  }
  get scrollOffset(): number {
    return this._store.$getScrollOffset();
  }
  get scrollSize(): number {
    return getScrollSize(this._store);
  }
  get viewportSize(): number {
    return this._store.$getViewportSize();
  }
  findItemIndex(offset: number): number {
    return this._layout.$findIndex(offset - this._store.$getStartSpacerSize());
  }
  getItemOffset(index: number): number {
    return this._store.$getItemOffset(index);
  }
  getItemSize(index: number): number {
    return this._layout.$getItemSize(index);
  }
  scrollToIndex(index: number, opts?: ScrollToIndexOpts): void {
    scrollToIndex(this.driver, this._store, this._layout, index, opts);
  }
  scrollTo(offset: number): void {
    scrollTo(this.driver, offset);
  }
  scrollBy(offset: number): void {
    scrollBy(this.driver, this._store, offset);
  }
}
