// src/solid/WindowVirtualizer.tsx
/**
 * @jsxImportSource solid-js
 */
import {
  onMount,
  onCleanup,
  createEffect,
  createSignal,
  createMemo,
  type JSX,
  type Accessor,
  on,
  For,
  untrack,
} from "solid-js";
import {
  UPDATE_SCROLL_END_EVENT,
  UPDATE_VIRTUAL_STATE,
  createVirtualStore,
  createListLayout,
  ACTION_ITEMS_LENGTH_CHANGE,
  UPDATE_SCROLL_EVENT,
  createWindowDriver,
  scrollToIndex,
  type ItemsRange,
  type ScrollToIndexOpts,
  type CacheSnapshot,
} from "../core/index.js";
import { ListItem } from "./ListItem.js";
import { isSameRange } from "./utils.js";

/**
 * Methods of {@link WindowVirtualizer}.
 */
export interface WindowVirtualizerHandle {
  /**
   * Get current {@link CacheSnapshot}.
   */
  readonly cache: CacheSnapshot;
  /**
   * Get current scrollTop, or scrollLeft if horizontal: true.
   */
  readonly scrollOffset: number;
  /**
   * Get current offsetHeight, or offsetWidth if horizontal: true.
   */
  readonly viewportSize: number;
  /**
   * Find nearest item index from offset.
   * @param offset offset in pixels from the start of the scroll container
   */
  findItemIndex(offset: number): number;
  /**
   * Get item offset from start.
   * @param index index of item
   */
  getItemOffset(index: number): number;
  /**
   * Get item size.
   * @param index index of item
   */
  getItemSize(index: number): number;
  /**
   * Scroll to the item specified by index.
   * @param index index of item
   * @param opts options
   */
  scrollToIndex(index: number, opts?: ScrollToIndexOpts): void;
}

/**
 * Props of {@link WindowVirtualizer}.
 */
export interface WindowVirtualizerProps<T> {
  /**
   * Get reference to {@link WindowVirtualizerHandle}.
   */
  ref?: (handle?: WindowVirtualizerHandle) => void;
  /**
   * The data items rendered by this component.
   */
  data: readonly T[];
  /**
   * The elements renderer function.
   */
  children: (data: T, index: Accessor<number>) => JSX.Element;
  /**
   * Extra item space in pixels to render before/after the viewport. The minimum value is 0. Lower value will give better performance but you can increase to avoid showing blank items in fast scrolling.
   * @defaultValue 200
   */
  bufferSize?: number;
  /**
   * Item size hint for unmeasured items in pixels. It will help to reduce scroll jump when items are measured if used properly.
   *
   * - If not set, initial item sizes will be automatically estimated from measured sizes. This is recommended for most cases.
   * - If set, you can opt out estimation and use the value as initial item size.
   */
  itemSize?: number;
  /**
   * While true is set, scroll position will be maintained from the end not usual start when items are added to/removed from start. It's recommended to set false if you add to/remove from mid/end of the list because it can cause unexpected behavior. This prop is useful for reverse infinite scrolling.
   */
  shift?: boolean;
  /**
   * If true, rendered as a horizontally scrollable list. Otherwise rendered as a vertically scrollable list.
   */
  horizontal?: boolean;
  /**
   * You can restore cache by passing a {@link CacheSnapshot} on mount. This is useful when you want to restore scroll position after navigation. The snapshot can be obtained from {@link WindowVirtualizerHandle.cache}.
   *
   * **The length of items should be the same as when you take the snapshot, otherwise restoration may not work as expected.**
   */
  cache?: CacheSnapshot;
  /**
   * Callback invoked whenever scroll offset changes.
   */
  onScroll?: () => void;
  /**
   * Callback invoked when scrolling stops.
   */
  onScrollEnd?: () => void;
}

/**
 * {@link Virtualizer} controlled by the window scrolling. See {@link WindowVirtualizerProps} and {@link WindowVirtualizerHandle}.
 */
export const WindowVirtualizer = <T,>(
  props: WindowVirtualizerProps<T>,
): JSX.Element => {
  let containerRef: HTMLDivElement | undefined;

  const {
    ref: _ref,
    data: _data,
    children: _children,
    itemSize,
    shift: _shift,
    horizontal = false,
    cache,
    onScrollEnd: _onScrollEnd,
  } = props;

  const layout = createListLayout(props.data.length, itemSize, cache);
  const store = createVirtualStore(layout, undefined, !itemSize);
  const driver = createWindowDriver(store, horizontal);

  const [stateVersion, setRerender] = createSignal(store.$getStateVersion());

  store.$subscribe(UPDATE_VIRTUAL_STATE, () => {
    setRerender(store.$getStateVersion());
  });
  store.$subscribe(UPDATE_SCROLL_EVENT, () => {
    // https://github.com/inokawa/virtua/discussions/580
    props.onScroll?.();
  });
  store.$subscribe(UPDATE_SCROLL_END_EVENT, () => {
    props.onScrollEnd?.();
  });

  const range = createMemo<ItemsRange>((prev) => {
    stateVersion();
    const next = store.$getRange(props.bufferSize);
    if (prev && isSameRange(prev, next)) {
      return prev;
    }
    return next;
  });
  const isScrolling = createMemo(() => stateVersion() && store.$isScrolling());
  const totalSize = createMemo(() => stateVersion() && store.$getTotalSize());
  const isNegative = createMemo(() => stateVersion() && driver.$isNegative());

  onMount(() => {
    if (props.ref) {
      props.ref({
        get cache() {
          return layout.$snapshot();
        },
        get scrollOffset() {
          return store.$getScrollOffset();
        },
        get viewportSize() {
          return store.$getViewportSize();
        },
        findItemIndex: store.$findItemIndex,
        getItemOffset: store.$getItemOffset,
        getItemSize: store.$getItemSize,
        scrollToIndex: (index, opts) =>
          scrollToIndex(driver, store, index, opts),
      });
    }

    driver.$observe(containerRef!);

    onCleanup(() => {
      if (props.ref) {
        props.ref();
      }

      store.$dispose();
      driver.$dispose();
    });
  });

  createEffect(
    on(stateVersion, () => {
      driver.$fixScrollJump();
    }),
  );

  const dataSlice = createMemo<T[]>(() => {
    const count = props.data.length;
    untrack(() => {
      if (count !== store.$getItemsLength()) {
        store.$update(ACTION_ITEMS_LENGTH_CHANGE, [count, props.shift]);
      }
    });
    const items: T[] = [];
    for (let [i, j] = range(); i <= j; i++) {
      items.push(props.data[i]!);
    }
    return items;
  });

  return (
    <div
      ref={containerRef}
      style={{
        contain: "size style", // https://github.com/inokawa/virtua/pull/775 https://github.com/inokawa/virtua/issues/800
        "overflow-anchor": "none", // opt out browser's scroll anchoring because it will conflict to scroll anchoring of virtualizer
        flex: "none", // flex style can break layout
        position: "relative",
        width: horizontal ? totalSize() + "px" : "100%",
        height: horizontal ? "100%" : totalSize() + "px",
        "pointer-events": isScrolling() ? "none" : undefined,
      }}
    >
      <For each={dataSlice()}>
        {(data, index) => {
          const itemIndex = createMemo(() => range()[0] + index());
          const offset = createMemo(() => {
            stateVersion();
            return store.$getItemOffset(itemIndex(), isNegative());
          });
          const hide = createMemo(() => {
            stateVersion();
            return store.$isUnmeasuredItem(itemIndex());
          });
          const children = createMemo(() => {
            return untrack(() => props.children(data, itemIndex));
          });

          return (
            <ListItem
              _index={itemIndex()}
              _resizer={driver.$observeItem}
              _offset={offset()}
              _hide={hide()}
              _children={children()}
              _isHorizontal={horizontal}
            />
          );
        }}
      </For>
    </div>
  );
};

// src/angular/WindowVirtualizer.ts
import {
  ApplicationRef,
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  ElementRef,
  type OnInit,
  TemplateRef,
  afterNextRender,
  afterRenderEffect,
  computed,
  contentChild,
  effect,
  inject,
  input,
  output,
  signal,
  untracked,
} from "@angular/core";
import { NgTemplateOutlet } from "@angular/common";
import {
  ACTION_ITEMS_LENGTH_CHANGE,
  type CacheSnapshot,
  type ScrollToIndexOpts,
  type StateVersion,
  UPDATE_SCROLL_END_EVENT,
  UPDATE_SCROLL_EVENT,
  UPDATE_VIRTUAL_STATE,
  createVirtualStore,
  createListLayout,
  createWindowDriver,
  type Driver,
  scrollToIndex,
} from "../core/index.js";
import { ListItem } from "./ListItem.js";
import { defaultGetKey, type ItemContext } from "./utils.js";

/**
 * Methods of {@link WindowVirtualizer}.
 */
export interface WindowVirtualizerHandle {
  /**
   * Get current {@link CacheSnapshot}.
   */
  readonly cache: CacheSnapshot;
  /**
   * Get current scrollTop, or scrollLeft if horizontal: true.
   */
  readonly scrollOffset: number;
  /**
   * Get current offsetHeight, or offsetWidth if horizontal: true.
   */
  readonly viewportSize: number;
  /**
   * Find nearest item index from offset.
   * @param offset offset in pixels from the start of the scroll container
   */
  findItemIndex(offset: number): number;
  /**
   * Get item offset from start.
   * @param index index of item
   */
  getItemOffset(index: number): number;
  /**
   * Get item size.
   * @param index index of item
   */
  getItemSize(index: number): number;
  /**
   * Scroll to the item specified by index.
   * @param index index of item
   * @param opts options
   */
  scrollToIndex(index: number, opts?: ScrollToIndexOpts): void;
}

/**
 * {@link Virtualizer} controlled by the window scrolling. See {@link WindowVirtualizerHandle}.
 *
 * The host element is the container of the items. Use the attribute selector to change its tag,
 * like `<ul virtuaWindowVirtualizer [data]="data">`.
 */
@Component({
  selector: "virtua-window-virtualizer, [virtuaWindowVirtualizer]",
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ListItem, NgTemplateOutlet],
  host: {
    "[style]": "containerStyle()",
  },
  template: `
    @for (item of items(); track item.key) {
      <div
        virtuaListItem
        [index]="item.index"
        [offset]="item.offset"
        [hide]="item.hide"
        [horizontal]="horizontal()"
        [resizer]="driver.$observeItem"
      >
        <ng-container
          [ngTemplateOutlet]="template()"
          [ngTemplateOutletContext]="{
            $implicit: item.data,
            index: item.index,
          }"
        />
      </div>
    }
  `,
})
export class WindowVirtualizer<T> implements OnInit, WindowVirtualizerHandle {
  /**
   * The data items rendered by this component.
   */
  readonly data = input.required<readonly T[]>();
  /**
   * Function that returns the key of an item in the list. It's recommended to specify whenever possible for performance.
   * @default defaultGetKey (returns index of item)
   */
  readonly getKey =
    input<(data: T, index: number) => string | number>(defaultGetKey);
  /**
   * Extra item space in pixels to render before/after the viewport. The minimum value is 0. Lower value will give better performance but you can increase to avoid showing blank items in fast scrolling.
   * @defaultValue 200
   */
  readonly bufferSize = input<number>();
  /**
   * Item size hint for unmeasured items in pixels. It will help to reduce scroll jump when items are measured if used properly.
   *
   * - If not set, initial item sizes will be automatically estimated from measured sizes. This is recommended for most cases.
   * - If set, you can opt out estimation and use the value as initial item size.
   */
  readonly itemSize = input<number>();
  /**
   * While true is set, scroll position will be maintained from the end not usual start when items are added to/removed from start. It's recommended to set false if you add to/remove from mid/end of the list because it can cause unexpected behavior. This prop is useful for reverse infinite scrolling.
   */
  readonly shift = input(false);
  /**
   * If true, rendered as a horizontally scrollable list. Otherwise rendered as a vertically scrollable list.
   */
  readonly horizontal = input(false);
  /**
   * You can restore cache by passing a {@link CacheSnapshot} on mount. This is useful when you want to restore scroll position after navigation. The snapshot can be obtained from {@link WindowVirtualizerHandle.cache}.
   *
   * **The length of items should be the same as when you take the snapshot, otherwise restoration may not work as expected.**
   */
  readonly cacheProp = input<CacheSnapshot>(undefined, { alias: "cache" });

  /**
   * Emitted whenever scroll offset changes.
   */
  // https://github.com/inokawa/virtua/discussions/580
  readonly scroll = output<void>();
  /**
   * Emitted when scrolling stops.
   */
  readonly scrollEnd = output<void>();

  /** @internal */
  protected template =
    contentChild.required<TemplateRef<ItemContext<T>>>(TemplateRef);

  /** @internal */
  private _store!: ReturnType<typeof createVirtualStore>;
  /** @internal */
  private _layout!: ReturnType<typeof createListLayout>;
  /** @internal */
  protected driver!: Driver;
  /** @internal */
  private _element: HTMLElement = inject(ElementRef).nativeElement;
  /** @internal */
  private _appRef = inject(ApplicationRef);

  /** @internal */
  private _stateVersion = signal<StateVersion>(undefined!);

  /** @internal */
  protected items = computed(() => {
    this._stateVersion(); // the store is not a signal, so depend on its version
    const store = this._store;
    const data = this.data();
    const getKey = this.getKey();
    const negative = this.driver.$isNegative();
    const [start, end] = store.$getRange(this.bufferSize());
    // https://github.com/inokawa/virtua/pull/847
    const items = [];
    for (let index = start; index <= end && index < data.length; index++) {
      const item = data[index]!;
      items.push({
        key: getKey(item, index),
        index,
        data: item,
        offset: store.$getItemOffset(index, negative),
        hide: store.$isUnmeasuredItem(index),
      });
    }
    return items;
  });

  /** @internal */
  protected containerStyle = computed(() => {
    this._stateVersion(); // the store is not a signal, so depend on its version
    const horizontal = this.horizontal();
    const totalSize = this._store.$getTotalSize();
    return {
      display: "block", // host of a custom element is inline by default
      contain: "size style", // https://github.com/inokawa/virtua/pull/775 https://github.com/inokawa/virtua/issues/800
      "overflow-anchor": "none", // opt out browser's scroll anchoring because it will conflict to scroll anchoring of virtualizer
      flex: "none", // flex style can break layout
      position: "relative",
      width: horizontal ? totalSize + "px" : "100%",
      height: horizontal ? "100%" : totalSize + "px",
      "pointer-events": this._store.$isScrolling() ? "none" : undefined,
    };
  });

  constructor() {
    effect(() => {
      const len = this.data().length;
      if (!this._store) return;
      if (len !== this._store.$getItemsLength()) {
        this._store.$update(ACTION_ITEMS_LENGTH_CHANGE, [
          len,
          untracked(this.shift),
        ]);
      }
    });

    afterNextRender({
      read: () => {
        this.driver.$observe(this._element);
      },
    });

    afterRenderEffect({
      read: () => {
        this._stateVersion();
        this.driver.$fixScrollJump();
      },
    });

    inject(DestroyRef).onDestroy(() => {
      this._store?.$dispose();
      this.driver?.$dispose();
    });
  }

  ngOnInit(): void {
    const itemSize = this.itemSize();
    const layout = (this._layout = createListLayout(
      this.data().length,
      itemSize,
      this.cacheProp(),
    ));
    const store = (this._store = createVirtualStore(layout));
    this.driver = createWindowDriver(store, this.horizontal());
    store.$subscribe(UPDATE_VIRTUAL_STATE, (sync) => {
      this._stateVersion.set(store.$getStateVersion());
      if (sync) {
        // The store requires the DOM to be updated synchronously, otherwise
        // imperative scroll may be clamped by the stale container size.
        this._appRef.tick();
      }
    });
    store.$subscribe(UPDATE_SCROLL_EVENT, () => {
      this.scroll.emit();
    });
    store.$subscribe(UPDATE_SCROLL_END_EVENT, () => {
      this.scrollEnd.emit();
    });
    this._stateVersion.set(store.$getStateVersion());
  }

  get cache(): CacheSnapshot {
    return this._layout.$snapshot();
  }
  get scrollOffset(): number {
    return this._store.$getScrollOffset();
  }
  get viewportSize(): number {
    return this._store.$getViewportSize();
  }
  findItemIndex(offset: number): number {
    return this._store.$findItemIndex(offset);
  }
  getItemOffset(index: number): number {
    return this._store.$getItemOffset(index);
  }
  getItemSize(index: number): number {
    return this._store.$getItemSize(index);
  }
  scrollToIndex(index: number, opts?: ScrollToIndexOpts): void {
    scrollToIndex(this.driver, this._store, index, opts);
  }
}
