// stories/angular/advanced/Chat.ts
import {
  Component,
  DestroyRef,
  afterRenderEffect,
  inject,
  signal,
  untracked,
  viewChild,
} from "@angular/core";
import { faker } from "@faker-js/faker";
import { Virtualizer } from "../../../src/angular";

type Data = {
  id: number;
  value: string;
  me?: boolean;
};

let id = 0;
const createItem = ({
  value = faker.lorem.paragraphs(1),
  me,
}: {
  value?: string;
  me?: boolean;
} = {}): Data => ({
  id: id++,
  value: value,
  me,
});

@Component({
  selector: "story-chat",
  imports: [Virtualizer],
  template: `
    <div
      style="width: 100vw; height: 100vh; display: flex; flex-direction: column;"
    >
      <div
        style="
          overflow-y: auto;
          flex: 1;
          /* opt out browser's scroll anchoring on header/footer because it will conflict to scroll anchoring of virtualizer */
          overflow-anchor: none;
          /* flex style for spacer */
          display: flex;
          flex-direction: column;
        "
      >
        <div
          style="
            /* spacer to align virtualizer to the bottom when all items are visible in the viewport */
            flex-grow: 1;
          "
        ></div>
        <div
          class="spinner"
          [style.visibility]="fetching() ? 'visible' : 'hidden'"
        >
          <span class="loader"></span>
        </div>
        <div
          virtuaVirtualizer
          [data]="items()"
          [shift]="isPrepend()"
          [startMargin]="spinnerHeight"
          [getKey]="getKey"
          (scroll)="onScroll($event)"
        >
          <ng-template let-item>
            @if (item.me === true) {
              <div
                style="border: solid 1px #ccc; background: lightyellow; padding: 10px; border-radius: 8px; white-space: pre-wrap; margin: 10px; margin-left: 160px;"
              >
                {{ item.value }}
              </div>
            } @else {
              <div
                style="border: solid 1px #ccc; background: #fff; padding: 10px; border-radius: 8px; white-space: pre-wrap; margin: 10px; margin-right: 160px;"
              >
                {{ item.value }}
              </div>
            }
          </ng-template>
        </div>
      </div>
      <form
        style="display: flex; flex-direction: column; margin: 10px;"
        (submit)="onSubmit($event)"
      >
        <textarea
          style="flex: 1;"
          rows="6"
          [value]="value()"
          (input)="onInput($event)"
          (keydown)="onKeyDown($event)"
        ></textarea>
        <div
          style="display: flex; flex-direction: row; gap: 8px; justify-content: flex-end;"
        >
          <button type="submit" [disabled]="!value().length">submit</button>
        </div>
      </form>
    </div>
  `,
  styles: [
    `
      .spinner {
        flex: none;
        height: 48px;
        display: flex;
        align-items: center;
        justify-content: center;
      }

      .loader {
        width: 24px;
        height: 24px;
        border-radius: 50%;
        border: 3px solid #ccc;
        border-top-color: transparent;
        animation: rotate 1s linear infinite;
      }

      @keyframes rotate {
        100% {
          transform: rotate(360deg);
        }
      }
    `,
  ],
})
export class ChatDemo {
  private readonly ref = viewChild(Virtualizer);

  protected readonly items = signal(
    Array.from({ length: 100 }, () => createItem()),
  );
  protected readonly value = signal("Hello world!");
  protected readonly isPrepend = signal(false);
  private readonly shouldStickToBottom = signal(true);
  protected readonly fetching = signal(false);

  protected readonly spinnerHeight = 48;

  protected readonly getKey = (d: Data) => d.id;

  constructor() {
    // Reset isPrepend after each update
    afterRenderEffect(() => {
      this.items();
      untracked(() => this.isPrepend.set(false));
    });

    // Auto-scroll to bottom when items change, or when it gets stuck to the bottom
    // again while the items around the destination are still being measured
    afterRenderEffect(() => {
      const lastItemIndex = this.items().length - 1;
      const shouldStickToBottom = this.shouldStickToBottom();
      untracked(() => {
        if (shouldStickToBottom) {
          this.ref()?.scrollToIndex(lastItemIndex, { align: "end" });
        }
      });
    });

    // Auto-add items timer
    let timer: ReturnType<typeof setTimeout> | null = null;
    const setTimer = () => {
      timer = setTimeout(() => {
        this.items.set([...this.items(), createItem()]);
        setTimer();
      }, 5000);
    };
    setTimer();
    inject(DestroyRef).onDestroy(() => {
      if (timer) {
        clearTimeout(timer);
      }
    });
  }

  protected async onScroll(offset: number): Promise<void> {
    const ref = this.ref();
    if (!ref) return;

    this.shouldStickToBottom.set(
      offset - this.spinnerHeight - ref.scrollSize + ref.viewportSize >= -1.5,
    );

    if (offset < this.spinnerHeight + 100 && !this.fetching()) {
      this.fetching.set(true);
      await new Promise((resolve) => setTimeout(resolve, 1000));
      this.isPrepend.set(true);
      this.items.set([
        ...Array.from({ length: 100 }, () => createItem()),
        ...this.items(),
      ]);
      this.fetching.set(false);
    }
  }

  protected onInput(e: Event): void {
    this.value.set((e.currentTarget as HTMLTextAreaElement).value);
  }

  protected onSubmit(e: Event): void {
    e.preventDefault();
    e.stopPropagation();
    this.submit();
  }

  protected onKeyDown(e: KeyboardEvent): void {
    if (e.code === "Enter" && (e.ctrlKey || e.metaKey)) {
      this.submit();
      e.preventDefault();
    }
  }

  private submit(): void {
    if (!this.value().length) return;
    this.shouldStickToBottom.set(true);
    this.items.set([
      ...this.items(),
      createItem({ value: this.value(), me: true }),
    ]);
    this.value.set("");
  }
}

// stories/svelte/advanced/Chat.svelte
<script lang="ts">
  import { Virtualizer, type VirtualizerHandle } from "../../../src/svelte";
  import { faker } from "@faker-js/faker";
  import { onMount } from "svelte";

  type Data = {
    id: number;
    value: string;
    me?: boolean;
  };

  let id = 0;
  const createItem = ({
    value = faker.lorem.paragraphs(1),
    me,
  }: {
    value?: string;
    me?: boolean;
  } = {}): Data => ({
    id: id++,
    value: value,
    me,
  });

  let items = $state(Array.from({ length: 100 }, () => createItem()));
  let value = $state("Hello world!");
  let ref: VirtualizerHandle;
  let shouldStickToBottom = $state(true);
  let isPrepend = $state(false);
  let fetching = $state(false);

  const spinnerHeight = 48;

  // Reset isPrepend after each update
  $effect(() => {
    items;
    isPrepend = false;
  });

  // Auto-scroll to bottom when items change
  $effect(() => {
    if (!ref) return;
    const lastItemIndex = items.length - 1;
    if (shouldStickToBottom) {
      ref.scrollToIndex(lastItemIndex, { align: "end" });
    }
  });

  // Auto-add items timer
  onMount(() => {
    let timer: ReturnType<typeof setTimeout> | null = null;

    const setTimer = () => {
      timer = setTimeout(() => {
        items = [...items, createItem()];
        setTimer();
      }, 5000);
    };

    setTimer();

    return () => {
      if (timer) {
        clearTimeout(timer);
      }
    };
  });

  const handleScroll = async (offset: number) => {
    if (!ref) return;

    shouldStickToBottom =
      offset - spinnerHeight - ref.getScrollSize() + ref.getViewportSize() >=
      -1.5;

    if (offset < spinnerHeight + 100 && !fetching) {
      fetching = true;
      await new Promise((resolve) => setTimeout(resolve, 1000));
      isPrepend = true;
      items = [...Array.from({ length: 100 }, () => createItem()), ...items];
      fetching = false;
    }
  };

  const disabled = $derived(!value.length);

  const submit = () => {
    if (disabled) return;
    shouldStickToBottom = true;
    items = [...items, createItem({ value, me: true })];
    value = "";
  };

  const handleKeyDown = (e: KeyboardEvent) => {
    if (e.code === "Enter" && (e.ctrlKey || e.metaKey)) {
      submit();
      e.preventDefault();
    }
  };
</script>

<div
  style="width: 100vw; height: 100vh; display: flex; flex-direction: column;"
>
  <div
    style="
    overflow-y: auto;
    flex: 1;
    /* opt out browser's scroll anchoring on header/footer because it will conflict to scroll anchoring of virtualizer */
    overflow-anchor: none;
    /* flex style for spacer */
    display: flex;
    flex-direction: column;
  "
  >
    <div
      style="
      /* spacer to align virtualizer to the bottom when all items are visible in the viewport */
      flex-grow: 1
    "
    ></div>
    <div class="spinner" style:visibility={fetching ? "visible" : "hidden"}>
      <span class="loader"></span>
    </div>
    <Virtualizer
      bind:this={ref}
      data={items}
      shift={isPrepend}
      startMargin={spinnerHeight}
      getKey={(d) => d.id}
      onscroll={handleScroll}
    >
      {#snippet children(item)}
        {#if item.me === true}
          <div
            style="border: solid 1px #ccc; background: lightyellow; padding: 10px; border-radius: 8px; white-space: pre-wrap; margin: 10px; margin-left: 160px;"
          >
            {item.value}
          </div>
        {:else}
          <div
            style="border: solid 1px #ccc; background: #fff; padding: 10px; border-radius: 8px; white-space: pre-wrap; margin: 10px; margin-right: 160px;"
          >
            {item.value}
          </div>
        {/if}
      {/snippet}
    </Virtualizer>
  </div>
  <form
    style="display: flex; flex-direction: column; margin: 10px;"
    onsubmit={(e) => {
      e.preventDefault();
      e.stopPropagation();
      submit();
    }}
  >
    <textarea style="flex: 1;" rows="6" bind:value onkeydown={handleKeyDown}
    ></textarea>
    <div
      style="display: flex; flex-direction: row; gap: 8px; justify-content: flex-end;"
    >
      <button type="submit" {disabled}> submit </button>
    </div>
  </form>
</div>

<style>
  .spinner {
    flex: none;
    height: 48px;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .loader {
    width: 24px;
    height: 24px;
    border-radius: 50%;
    border: 3px solid #ccc;
    border-top-color: transparent;
    animation: rotate 1s linear infinite;
  }

  @keyframes rotate {
    100% {
      transform: rotate(360deg);
    }
  }
</style>
