// src/solid/ListItem.tsx
/**
 * @jsxImportSource solid-js
 */
import { ItemResizeObserver } from "../core/resizer";
import { isRTLDocument } from "../core/environment";
import { Component, JSX, createEffect, createMemo, onCleanup } from "solid-js";

interface ListItemProps {
  _children: JSX.Element;
  _resizer: ItemResizeObserver;
  _index: number;
  _offset: number;
  _hide: boolean;
  _isHorizontal: boolean;
}

/**
 * @internal
 */
export const ListItem: Component<ListItemProps> = (props) => {
  let elementRef: HTMLDivElement | undefined;

  // The index may be changed if elements are inserted to or removed from the start of props.children
  createEffect(() => {
    if (!elementRef) return;
    onCleanup(props._resizer(elementRef, props._index));
  });

  const style = createMemo(() => {
    const isHorizontal = props._isHorizontal;
    const style: JSX.CSSProperties = {
      margin: 0,
      padding: 0,
      position: "absolute",
      [isHorizontal ? "height" : "width"]: "100%",
      [isHorizontal ? "top" : "left"]: "0px",
      [isHorizontal ? (isRTLDocument() ? "right" : "left") : "top"]:
        props._offset + "px",
      visibility: props._hide ? "hidden" : "visible",
    };
    if (isHorizontal) {
      style.display = "flex";
    }
    return style;
  });

  return (
    <div ref={elementRef} style={style()}>
      {props._children}
    </div>
  );
};

// src/svelte/ListItem.svelte
<script lang="ts">
  import { afterUpdate, onDestroy } from "svelte";
  import { isRTLDocument, type ItemResizeObserver } from "./core";
  import { styleToString } from "./utils";

  export let index: number;
  export let offset: number;
  export let hide: boolean;
  export let horizontal: boolean;
  export let resizer: ItemResizeObserver;

  let elementRef: HTMLDivElement;

  let cleanupResizer: (() => void) | undefined;
  // The index may be changed if elements are inserted to or removed from the start of props.children
  let prevIndex: number | undefined;
  afterUpdate(() => {
    if (prevIndex === index) return;
    if (cleanupResizer) cleanupResizer();
    cleanupResizer = resizer(elementRef, (prevIndex = index));
  });
  onDestroy(() => {
    if (cleanupResizer) cleanupResizer();
  });

  let style: string;
  $: {
    const _style: Record<string, string> = {
      margin: "0px",
      padding: "0px",
      position: "absolute",
      [horizontal ? "height" : "width"]: "100%",
      [horizontal ? "top" : "left"]: "0px",
      [horizontal ? (isRTLDocument() ? "right" : "left") : "top"]:
        offset + "px",
      visibility: hide ? "hidden" : "visible",
    };
    if (horizontal) {
      _style["display"] = "flex";
    }

    style = styleToString(_style);
  }
</script>

<div bind:this={elementRef} {style}>
  <slot />
</div>
