// src/solid/types.ts
import { JSX, ParentComponent } from "solid-js";

export type ViewportComponentAttributes = Pick<
  JSX.HTMLAttributes<HTMLElement>,
  "class" | "id" | "role" | "tabIndex" | "onKeyDown" | "onWheel"
> &
  JSX.AriaAttributes & { style?: JSX.CSSProperties };

export interface CustomContainerComponentProps {
  style: JSX.CSSProperties;
  children: JSX.Element;
  ref?: any | (() => any);
}

export type CustomContainerComponent =
  ParentComponent<CustomContainerComponentProps>;

/**
 * Props of customized item component for {@link Virtualizer} or {@link WindowVirtualizer}.
 */
export interface CustomItemComponentProps {
  style: JSX.CSSProperties;
  index: number;
  children: JSX.Element;
  ref?: any | (() => any);
}

export type CustomItemComponent = ParentComponent<CustomItemComponentProps>;

// src/react/types.ts
import { CSSProperties, ReactNode } from "react";

export type ViewportComponentAttributes = Pick<
  React.HTMLAttributes<HTMLElement>,
  "className" | "style" | "id" | "role" | "tabIndex" | "onKeyDown" | "onWheel"
> &
  React.AriaAttributes;

export interface CustomContainerComponentProps {
  style: CSSProperties;
  children: ReactNode;
}

export type CustomContainerComponent = React.ForwardRefExoticComponent<
  React.PropsWithoutRef<CustomContainerComponentProps> &
    React.RefAttributes<any>
>;

/**
 * Props of customized item component for {@link Virtualizer} or {@link WindowVirtualizer}.
 */
export interface CustomItemComponentProps {
  style: CSSProperties;
  index: number;
  children: ReactNode;
}

export type CustomItemComponent = React.ForwardRefExoticComponent<
  React.PropsWithoutRef<CustomItemComponentProps> & React.RefAttributes<any>
>;
