// stories/svelte/Horizontal.svelte
<script lang="ts">
  import { VList } from "../../src/svelte";

  const sizes = [40, 180, 77];
  const createItem = (i: number) => ({ id: i, size: sizes[i % 4] + "px" });

  const data = Array.from({ length: 1000 }).map((_, i) => createItem(i));
</script>

<div style="padding: 10px;">
  <VList
    {data}
    let:item
    style={`width: 100%; height: 200px;`}
    getKey={(d) => d.id}
    horizontal
  >
    <div
      style={`
      width: ${item.size};
      background: white;
      border-right: solid 1px #ccc;
    `}
    >
      {item.id}
    </div>
  </VList>
</div>

// stories/vue/basics/Horizontal.vue
<script setup lang="ts">
import { VList } from '../../../src/vue'

const sizes = [40, 180, 77];
const data = Array.from({ length: 1000 }).map((_, i) => sizes[i % 3]);
</script>

<template>
  <div :style="{ padding: '10px' }">
    <VList :data="data" :style="{ width: '100%', height: '200px' }" horizontal #default="{ item, index }">
      <div :key="index" :style="{ width: item + 'px', background: 'white', borderRight: 'solid 1px #ccc' }">
        {{ index }}
      </div>
    </VList>
  </div>
</template>

<style scoped>
/* NOP */
</style>
