// stories/svelte/basics/Nested.svelte
<script lang="ts">
  import { Virtualizer } from "../../../src/svelte";

  const sizes = [20, 40, 80, 77];

  const data = Array.from({ length: 1000 }).map((_, i) => sizes[i % 4]!);

  const outerPadding = 40;
  const innerPadding = 60;
  let scrollRef: HTMLElement = $state();
</script>

<div
  bind:this={scrollRef}
  style={`
  width: 100%;
  height: 100vh;
  overflow-y: auto;
  /* opt out browser's scroll anchoring on header/footer because it will conflict with scroll anchoring of virtualizer */
  overflow-anchor: none;
`}
>
  <div style="background-color: burlywood; padding: {outerPadding}px;">
    <div style="background-color: steelblue; padding: {innerPadding}px;">
      <Virtualizer
        {data}
        getKey={(_, i) => i}
        {scrollRef}
        startMargin={outerPadding + innerPadding}
      >
        {#snippet children(item, index)}
          <div
            style="
              height: {item}px;
              background: white;
              border-bottom: solid 1px #ccc;
            "
          >
            {index}
          </div>
        {/snippet}
      </Virtualizer>
    </div>
  </div>
</div>

// stories/vue/basics/Nested.vue
<script setup lang="ts">
import { ref } from "vue";
import { Virtualizer } from "../../../src/vue";

const sizes = [20, 40, 80, 77];
const data = Array.from({ length: 1000 }).map((_, i) => sizes[i % 4]);

const outerPadding = 40;
const innerPadding = 60;
const scrollRef = ref<HTMLElement>();
</script>

<template>
  <div
    ref="scrollRef"
    :style="{
      width: '100%',
      height: '100vh',
      overflowY: 'auto',
      // opt out browser's scroll anchoring on header/footer because it will conflict with scroll anchoring of virtualizer
      overflowAnchor: 'none',
    }"
  >
    <div
      :style="{ backgroundColor: 'burlywood', padding: outerPadding + 'px' }"
    >
      <div
        :style="{ backgroundColor: 'steelblue', padding: innerPadding + 'px' }"
      >
        <Virtualizer
          :data="data"
          #default="{ item, index }"
          :scrollRef="scrollRef"
          :startMargin="outerPadding + innerPadding"
        >
          <div
            :key="index"
            :style="{
              height: item + 'px',
              background: 'white',
              borderBottom: 'solid 1px #ccc',
            }"
          >
            {{ index }}
          </div>
        </Virtualizer>
      </div>
    </div>
  </div>
</template>

<style scoped>
/* NOP */
</style>
